services:
  app:
    build: .
    ports:
      - "3100:3100"
    env_file:
      - .env
    environment:
      PORT: "3100"
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./uploads:/app/uploads
      - ./sqlite.db:/app/sqlite.db
      - ./sqlite.db-wal:/app/sqlite.db-wal
      - ./sqlite.db-shm:/app/sqlite.db-shm
    restart: unless-stopped
